### ISSUE TITLE
Please provide support for FreePascal compiler

### ISSUE THREAD

**Issue by roseswe** [ncs-sniper/Lib.SHA2#1]
fpc  SHA2.pas 
Linux Build
Free Pascal Compiler version 2.6.4 [2016/04/28] for x86_64
Copyright (c) 1993-2014 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling SHA2.pas
SHA2.pas(191,46) Fatal: Syntax error, ":" expected but "identifier HASH" found
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode (normal if you did not specify a source file to be compiled)

**Comment by ncs-sniper** [comment]
FPC can compile it, but make sure to use delphi or objfpc (with $H+) modes, since default mode (fpc) seems to not support some constructs (out parameters in this case).
I was developing this unit in Lazarus, which adds proper modes for all project files, that is why I have not noticed it is missing - I will add proper mode to all my libs asap.

**Comment by roseswe** [comment]
Then we have another compiler error:

ralph:~/Downloads/SHA > fpc -Mobjfpc SHA2.pas 
Linux Build
Free Pascal Compiler version 2.6.4 [2016/04/28] for x86_64
Copyright (c) 1993-2014 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling SHA2.pas
Compiling BitOps.pas
BitOps.pas(296,46) Error: Identifier not found "TNibble"
BitOps.pas(297,45) Error: Identifier not found "TNibble"
-----------------
ralph:~/Downloads/SHA > fpc  SHA2.pas 
Linux Build
Free Pascal Compiler version 2.6.4 [2016/04/28] for x86_64
Copyright (c) 1993-2014 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling SHA2.pas
SHA2.pas(191,46) Fatal: Syntax error, ":" expected but "identifier HASH" found
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode (normal if you did not specify a source file to be compiled)

**Comment by ncs-sniper** [comment]
Dependencies - you have to also add AuxTypes (https://github.com/ncs-sniper/Lib.AuxTypes), BitOps unit requires it (almost all my libs do require it).

**Comment by ncs-sniper** [comment]
It should be ok now - as long as you will have all required dependencies.
I have also added symbol BARE_FPC (disabled by default) for compilation outside of Lazarus - you probably have to define it (inside of the unit or as a compilation parameter) for your needs.
Please let me know whether it works.

**Comment by roseswe** [comment]
works now like a charm
